### PR TITLE
Chirps read side

### LINKED ISSUE #24: Chirp tables may fail to be created if cassandra is not up
The chirp table are created as part of the chirp service initialization https://github.com/lagom/activator-lagom-java-chirper/blob/master/chirp-impl/src/main/java/sample/chirper/chirp/impl/ChirpServiceImpl.java#L52-L64. If Cassandra is not up (e.g., it's in the process of being started), then the chirp tables won't be created. To avoid the issue, the table should be created only when a connection with the Cassandra server can be established.

### PR DESCRIPTION
**Pull request by TimMoore**
This makes the list of old chirps eventually consistent, but it fixes #24 and allows Chirper to run in the ConductR sandbox.

### CODE REVIEW

File: chirp-impl/src/main/java/sample/chirper/chirp/impl/ChirpServiceImpl.java [hunk 1]
```diff
@@ -3,162 +3,80 @@
...
-          sources.add(topic.subscriber());
-        }
-        HashSet<String> users = new HashSet<>(req.userIds);
-        Source<Chirp, ?> publishedChirps = Source.from(sources).flatMapMerge(sources.size(), s -> s)
-          .filter(c -> users.contains(c.userId));
+public class ChirpServiceImpl implements ChirpService {
+    private final PersistentEntityRegistry persistentEntitites;
+    private final ChirpTopic topic;
+    private final ChirpRepository chirps;
+    private final CassandraSession db;
```
Comment (ignasi35) [inline chirp-impl/src/main/java/sample/chirper/chirp/impl/ChirpServiceImpl.java:30]: The `db`  is probably not needed now.

File: chirp-impl/src/main/java/sample/chirper/chirp/impl/ChirpServiceImpl.java [hunk 2]
```diff
@@ -3,162 +3,80 @@
...
-            return TreePVector.from(chirps);
-          });
-      results = results.plus(result);
+    @Override
+    public ServiceCall<LiveChirpsRequest, Source<Chirp, ?>> getLiveChirps() {
+        return req -> chirps.getRecentChirps(req.userIds).thenApply(recentChirps -> {
+            List<Source<Chirp, ?>> sources = new ArrayList<>();
+            for (String userId : req.userIds) {
+                sources.add(topic.subscriber(userId));
+            }
```
Comment (ignasi35) [inline chirp-impl/src/main/java/sample/chirper/chirp/impl/ChirpServiceImpl.java:62]: if/when a userIds contains duplicates, will those be repeated hits on DB? and the, will we build duplicate `Source`'s?

File: chirp-impl/src/main/java/sample/chirper/chirp/impl/ChirpServiceImpl.java (hunk 1 above)
Comment (TimMoore) [reply chirp-impl/src/main/java/sample/chirper/chirp/impl/ChirpServiceImpl.java:30]: Yes, good catch. I thought I had cleaned up all of the unused fields!

File: chirp-impl/src/main/java/sample/chirper/chirp/impl/ChirpServiceImpl.java (hunk 2 above)
Comment (TimMoore) [reply chirp-impl/src/main/java/sample/chirper/chirp/impl/ChirpServiceImpl.java:62]: Yes, I suppose that's true. Right now it relies on the fact that no queries with duplicate IDs will ever be made.

If you think it's worth de-duplicating on the back end, let's do that in a separate PR.

File: chirp-impl/src/main/java/sample/chirper/chirp/impl/ChirpTimelineEntity.java [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+    ChirpTimelineEntity(ChirpTopic topic) {
+        this.topic = topic;
+    }
+
+    @Override
+    public Behavior initialBehavior(Optional<NotUsed> snapshotState) {
+        BehaviorBuilder b = newBehaviorBuilder(NotUsed.getInstance());
+        b.setCommandHandler(AddChirp.class, this::addChirp);
+        b.setEventHandler(ChirpAdded.class, evt -> state());
+        return b.build();
```
Comment (TimMoore) [inline chirp-impl/src/main/java/sample/chirper/chirp/impl/ChirpTimelineEntity.java:25]: BTW I get a bunch of unchecked assignment warnings from IntelliJ in this method and also on the `ctx.reply` call below.

- Unchecked assignment: 'com.lightbend.lagom.javadsl.persistence.PersistentEntity.BehaviorBuilder' to 'com.lightbend.lagom.javadsl.persistence.PersistentEntity.BehaviorBuilder'
- Unchecked assignment: 'com.lightbend.lagom.javadsl.persistence.PersistentEntity.Behavior' to 'com.lightbend.lagom.javadsl.persistence.PersistentEntity.Behavior'
- Unchecked call to 'reply(R)' as a member of raw type 'com.lightbend.lagom.javadsl.persistence.PersistentEntity.ReadOnlyCommandContext'

I'm not totally sure what's wrong... possibly because those inner classes inherit a type parameter from the enclosing class?

**Comment by TimMoore** [comment]
Ah whoops I had another commit to push with the fix from Ignasi's comment! I'll open a second PR.

File: chirp-impl/src/main/java/sample/chirper/chirp/impl/ChirpTimelineEntity.java (hunk 3 above)
Comment (ignasi35) [reply chirp-impl/src/main/java/sample/chirper/chirp/impl/ChirpTimelineEntity.java:25]: Strangely enough, `sbt` is configured to call `javac` using `-Xlint:unchecked` (as suggested by IntelliJ to obtain more details) and no warning is displayed.

Comment (TimMoore) [reply chirp-impl/src/main/java/sample/chirper/chirp/impl/ChirpTimelineEntity.java:25]: Yes, I think it must be a bug in IntelliJ
